image:
    file: .gitpod.dockerfile
ports:
    - port: 8080
tasks:
    - init: >
        cp .env.example .env;
        pipenv install;
        pipenv run init;
        pipenv run migrate;


    - command: >
        pipenv run start;



